import streamlit as st
import os
import json
import io
import pandas as pd
import plotly.express as px
from datetime import datetime
from groq import Groq
from dotenv import load_dotenv

# PDF Generation Imports
from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

# 1. SETUP & CONFIG
load_dotenv()
st.set_page_config(page_title="Shelfie AI | Executive Suite", layout="wide")

if "history" not in st.session_state:
    st.session_state.history = []

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# 2. PDF ENGINE (Updated for new features)
def generate_pdf(data):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"Shelfie AI: Intelligence Report", styles['Title']))
    story.append(Paragraph(f"Document: {data['title']}", styles['Heading2']))
    story.append(Paragraph(f"Generated by: {data['user']} on {data['timestamp']}", styles['Normal']))
    story.append(Spacer(1, 12))

    # Narrative Stats
    story.append(Paragraph(f"Word Count: {data['word_count']} | Est. Reading Time: {data['reading_time']}", styles['Italic']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Executive Summary", styles['Heading3']))
    story.append(Paragraph(data['summary'], styles['Normal']))
    story.append(Spacer(1, 12))

    # Stats Table
    table_data = [
        ["Classification", "Safety Rating", "Primary Sentiment"],
        [data['genre'], data['profanity'], data['sentiment']]
    ]
    t = Table(table_data, colWidths=[150, 150, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # Characters Section
    if data['characters']:
        story.append(Paragraph("Key Characters", styles['Heading3']))
        for char, desc in data['characters'].items():
            story.append(Paragraph(f"<b>{char}</b>: {desc}", styles['Normal']))
        story.append(Spacer(1, 12))

    story.append(Paragraph("Key Takeaways", styles['Heading3']))
    for point in data['takeaways']:
        story.append(Paragraph(f"• {point}", styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer

# 3. AI LOGIC (Updated prompt)
def analyze_text(text):
    system_prompt = (
        "You are an Elite Literary Critic. Analyze the text and return a JSON object. "
        "Include keys: 'genre', 'summary', 'profanity_level', 'themes', 'target_audience', 'takeaways', 'sentiment', "
        "'feature_sentiment' (a dictionary of themes/features and their sentiment score 1-10), "
        "'characters' (a dictionary of character names and their descriptions)."
    )
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": text[:15000]}],
            response_format={"type": "json_object"}
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        return {"error": str(e)}

def get_smart_value(data, key, fallback_text):
    val = data.get(key) or data.get(key.capitalize()) or data.get(key.upper())
    return val if val else fallback_text

# 4. SIDEBAR
with st.sidebar:
    st.title("📚 Scan History")
    if not st.session_state.history:
        st.info("No scans recorded yet.")
    else:
        for idx, entry in enumerate(reversed(st.session_state.history)):
            with st.expander(f"{entry['title'][:20]}"):
                st.caption(f"👤 {entry['user']} | 📅 {entry['timestamp']}")
                st.write(f"Words: {entry['word_count']}")
                pdf_data = generate_pdf(entry)
                st.download_button("💾 Download PDF", pdf_data, f"Shelfie_{entry['title']}.pdf", "application/pdf", key=f"dl_{idx}")

# 5. MAIN INTERFACE
st.title("Shelfie Bot - Admin Final Iteration Console")
st.markdown("---")

col_input, col_output = st.columns([1, 1.2], gap="large")

with col_input:
    st.subheader("Source Content")
    user_name = st.text_input("Uploader Name", value="Executive Admin")
    book_title = st.text_input("Document/Book Title", placeholder="Enter title...")
    uploaded_file = st.file_uploader("Upload Text File", type=["txt"])
    
    raw_text = ""
    if uploaded_file:
        raw_text = uploaded_file.read().decode("utf-8")
        if not book_title: book_title = uploaded_file.name

    user_text = st.text_area("Content Analysis Window", value=raw_text, height=350)
    analyze_button = st.button("🚀 GENERATE EXECUTIVE REPORT", width=True)

with col_output:
    st.subheader("Intelligence Report")
    
    if analyze_button:
        if len(user_text) < 100:
            st.warning("Insufficient text for analysis.")
        else:
            with st.spinner("Processing Neural Mapping..."):
                # Logic for Word Count & Reading Time
                words = user_text.split()
                word_count = len(words)
                # Average reading speed is ~238 WPM
                minutes = word_count / 238
                read_time = f"{int(minutes)}m {int((minutes % 1) * 60)}s" if minutes >= 1 else f"{int(minutes * 60)}s"

                data = analyze_text(user_text)
                
                if "error" in data:
                    st.error("Neural engine busy.")
                else:
                    report_data = {
                        "title": book_title if book_title else "Unnamed",
                        "user": user_name,
                        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
                        "genre": get_smart_value(data, "genre", "General"),
                        "profanity": get_smart_value(data, "profanity_level", "Low"),
                        "summary": get_smart_value(data, "summary", "N/A"),
                        "takeaways": get_smart_value(data, "takeaways", []),
                        "sentiment": get_smart_value(data, "sentiment", "Neutral"),
                        "word_count": word_count,
                        "reading_time": read_time,
                        "characters": data.get("characters", {}),
                        "feature_sentiment": data.get("feature_sentiment", {})
                    }
                    st.session_state.history.append(report_data)

                    # --- DISPLAY UI ---
                    # Row 1: Key Metrics
                    m1, m2, m3, m4 = st.columns(4)
                    m1.metric("Words", report_data['word_count'])
                    m2.metric("Reading Time", report_data['reading_time'])
                    m3.metric("Sentiment", report_data['sentiment'])
                    m4.metric("Safety", report_data['profanity'])
                    
                    # Row 2: Sentiment Bar Chart
                    if report_data['feature_sentiment']:
                        st.markdown("### Feature Sentiment Map")
                        df = pd.DataFrame(list(report_data['feature_sentiment'].items()), columns=['Feature', 'Score'])
                        fig = px.bar(df, x='Feature', y='Score', color='Score', color_continuous_scale='RdYlGn', range_y=[0,10])
                        st.plotly_chart(fig, width=True)

                    st.markdown("### Executive Summary")
                    st.write(report_data['summary'])
                    
                    # Characters Section
                    if report_data['characters']:
                        st.markdown("### Character Analysis")
                        for char, desc in report_data['characters'].items():
                            st.markdown(f"**{char}**: {desc}")

                    st.markdown("### Key Takeaways")
                    for item in report_data['takeaways']:
                        st.write(f"• {item}")
                    
                    st.markdown("---")
                    pdf_bytes = generate_pdf(report_data)
                    st.download_button("📄 EXPORT TO PDF", pdf_bytes, f"Shelfie_Report_{report_data['title']}.pdf", "application/pdf", width=True)

st.markdown("---")
st.caption("Shelfie AI v1.7 | System Admin Status: Active")