import streamlit as st
import os
import json
import io
from datetime import datetime
from groq import Groq
from dotenv import load_dotenv

# PDF Generation Imports
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

# 1. SETUP & CONFIG
load_dotenv()
st.set_page_config(page_title="Shelfie AI | Executive Suite", layout="wide")

# Initialize Session State
if "history" not in st.session_state:
    st.session_state.history = []

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# 2. PDF ENGINE
def generate_pdf(data):
    """Generates a professional PDF report from the analysis data."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER)
    styles = getSampleStyleSheet()
    story = []

    # Title & Metadata
    story.append(Paragraph(f"Shelfie AI: Intelligence Report", styles['Title']))
    story.append(Paragraph(f"Document: {data['title']}", styles['Heading2']))
    story.append(Paragraph(f"Generated by: {data['user']} on {data['timestamp']}", styles['Normal']))
    story.append(Spacer(1, 12))

    # Summary Section
    story.append(Paragraph("Executive Summary", styles['Heading3']))
    story.append(Paragraph(data['summary'], styles['Normal']))
    story.append(Spacer(1, 12))

    # Stats Table
    table_data = [
        ["Classification", "Safety Rating", "Sentiment"],
        [data['genre'], data['profanity'], data['sentiment']]
    ]
    t = Table(table_data, colWidths=[150, 150, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # Insights
    story.append(Paragraph("Key Takeaways", styles['Heading3']))
    for point in data['takeaways']:
        story.append(Paragraph(f"• {point}", styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer

# 3. AI LOGIC
def analyze_text(text):
    system_prompt = (
        "You are an Elite Literary Critic. Analyze the text and return a JSON object. "
        "Include keys: 'genre', 'summary', 'profanity_level', 'themes', 'target_audience', 'takeaways', 'sentiment'. "
        "Do not leave any field empty."
    )
    
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text[:15000]}
            ],
            response_format={"type": "json_object"}
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        return {"error": str(e)}

def get_smart_value(data, key, fallback_text):
    val = data.get(key) or data.get(key.capitalize()) or data.get(key.upper())
    return val if val else fallback_text

# 4. SIDEBAR
with st.sidebar:
    st.title("📚 Scan History")
    if not st.session_state.history:
        st.info("No scans recorded yet.")
    else:
        for idx, entry in enumerate(reversed(st.session_state.history)):
            with st.expander(f"{entry['title'][:20]}"):
                st.caption(f"👤 {entry['user']} | 📅 {entry['timestamp']}")
                st.write(f"**Genre:** {entry['genre']}")
                # Quick Download from History
                pdf_data = generate_pdf(entry)
                st.download_button(
                    label="💾 Download PDF",
                    data=pdf_data,
                    file_name=f"Shelfie_{entry['title']}.pdf",
                    mime="application/pdf",
                    key=f"dl_{idx}"
                )

# 5. MAIN INTERFACE
st.title("Shelfie Bot - Admin Final Iteration Console")
st.markdown("---")

col_input, col_output = st.columns([1, 1], gap="large")

with col_input:
    st.subheader("Source Content")
    user_name = st.text_input("Uploader Name", value="Executive Admin")
    book_title = st.text_input("Document/Book Title", placeholder="Enter title...")
    
    uploaded_file = st.file_uploader("Upload Text File", type=["txt"])
    
    raw_text = ""
    if uploaded_file:
        raw_text = uploaded_file.read().decode("utf-8")
        if not book_title:
            book_title = uploaded_file.name

    user_text = st.text_area("Content Analysis Window", value=raw_text, height=300)
    analyze_button = st.button("🚀 GENERATE EXECUTIVE REPORT", use_container_width=True)

with col_output:
    st.subheader("Intelligence Report")
    
    if analyze_button:
        if len(user_text) < 100:
            st.warning("Insufficient text for deep analysis.")
        else:
            with st.spinner("Processing Neural Mapping..."):
                data = analyze_text(user_text)
                
                if "error" in data:
                    st.error("Neural engine busy. Try again.")
                else:
                    # Clean data with smart fallbacks
                    report_data = {
                        "title": book_title if book_title else "Unnamed Analysis",
                        "user": user_name,
                        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
                        "genre": get_smart_value(data, "genre", "General"),
                        "profanity": get_smart_value(data, "profanity_level", "Low"),
                        "summary": get_smart_value(data, "summary", "No summary available."),
                        "themes": get_smart_value(data, "themes", ["General"]),
                        "audience": get_smart_value(data, "target_audience", "General"),
                        "takeaways": get_smart_value(data, "takeaways", []),
                        "sentiment": get_smart_value(data, "sentiment", "Neutral")
                    }
                    
                    # Save to History
                    st.session_state.history.append(report_data)

                    # DISPLAY UI
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Genre", report_data['genre'])
                    m2.metric("Safety", report_data['profanity'])
                    m3.metric("Sentiment", report_data['sentiment'])
                    
                    st.markdown("### Executive Summary")
                    st.write(report_data['summary'])
                    
                    st.markdown("### Key Takeaways")
                    for item in report_data['takeaways']:
                        st.write(f"• {item}")
                    
                    st.markdown("---")
                    # Immediate Download Option
                    pdf_bytes = generate_pdf(report_data)
                    st.download_button(
                        label="📄 EXPORT TO PDF",
                        data=pdf_bytes,
                        file_name=f"Shelfie_Report_{report_data['title']}.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )

# FOOTER
st.markdown("---")
st.caption("Shelfie AI v1.4 | System Admin Status: Active")